config/routes.rb
JRubyHub::Application.routes.draw do |map|
  resources :items

  root :to => "home#index"

end

app/models/attached_to_ref_node.rb
module AttachedToRefNode
  def self.included(klass)
    ::Neo4j::ReferenceNode.has_one(klass.name.underscore.to_sym).to(klass)
    klass.after_create :after_create_add_to_ref_node
    klass.instance_eval do
      def instance
        obj = Neo4j.ref_node.send(name.underscore.to_sym)
        raise "No #{name} found!" if obj.nil?
        obj
      end
    end
  end

  private
  def after_create_add_to_ref_node
    Neo4j.ref_node.send("#{self.class.name.underscore}=".to_sym, self)
  end
end

app/models/item.rb
class Item < Neo4j::Model
  property :content
  property :created_at, :type => DateTime

  index :content, :created_at

  before_create :before_create_set_timestamp
  after_create :after_create_add_to_item_list

  def prev
    item = list(:items).prev
    return nil if ItemList === item
    item
  end

  def next
    list(:items).next
  end

  def self.css_name
    model_name.underscore
  end

  private
  def before_create_set_timestamp
    self.created_at ||= DateTime.now
  end

  def after_create_add_to_item_list
    ItemList << self
  end
end

app/models/item_list.rb
class ItemList < Neo4j::Model
  has_list :items, :counter => true
  has_one :tail
  include AttachedToRefNode

  def <<(item)
    items << item
    self.tail = item if tail.nil?
    self
  end

  def head
    items.first
  end

  def method_missing(meth,*args,&block)
    return items.send(meth,*args,&block) if items.respond_to?(meth)
    super
  end

  def self.method_missing(meth,*args,&block)
    instance.send(meth,*args,&block)
  end

  def self.enumerator(limit = nil)
    return Enumerator.new(limit)
  end

  class Enumerator
    include Enumerable
    def initialize(limit)
      @limit = limit.to_i
      @limit = nil if @limit <= 0
      @current = ItemList.head
    end

    def each
      while @current
        yield @current
        if @limit
          @limit -= 1
          return if @limit <= 0
        end
        @current = @current.next
      end
    end
  end
end

app/models/tweet.rb
class Tweet < Item
  property :profile_image_url, :from_user, :to_user_id,
    :tweet_id, :from_user_id, :iso_language_code, :source
  property :metadata, :type => Hash
  property :geo, :type => Hash

  index :from_user, :content, :created_at

  def self.from_data(hash)
    attr_arr = hash.map do |k,v|
      case k
      when "id"
        [:tweet_id, v]
      when "created_at"
        [:created_at, v.to_datetime]
      when "text"
        [:content, v]
      else
        [k.to_sym, v]
      end
    end
    attrs = Hash[*attr_arr.flatten]
    create!(attrs)
  end
end

app/models/tweet_spider.rb
require 'uri'
require 'rest_client'

class TweetSpider < Neo4j::Model
  include AttachedToRefNode
  PROPERTIES = [:query, :refresh_url, :since_id, :max_id]
  PAGES_IN_BATCH = 10
  property *PROPERTIES
  attr_writer :fetcher

  def fetch_query
    if refresh_url
      refresh_url
    elsif query
      "?q=#{URI.escape query}"
    end
  end

  def fetcher
    @fetcher ||= TwitterFetcher.new(fetch_query)
  end

  def fetch_tweet_data
    ActiveSupport::JSON.decode(fetcher.read).tap do |result|
      if Array === result["results"]
        result["results"].each do |tweet|
          tweet["created_at"] = Time.rfc2822(tweet["created_at"])
        end
      end
    end
  rescue => e
    Rails.logger.warn "Unable to fetch tweets: #{e.inspect}"
    Rails.logger.debug("  " + e.backtrace.join("\n  "))
    props.dup
  end

  def load_next_page(pages_to_load, data)
    @fetcher = TwitterFetcher.new(data["next_page"]) if data["next_page"]
    if pages_to_load > 1
      next_page_data = fetch_tweet_data
      if next_page_data["results"] && !next_page_data["results"].empty?
        data["results"]  += next_page_data["results"]
        data["next_page"] = next_page_data["next_page"]
        data["page"]      = next_page_data["page"]
        load_next_page(pages_to_load - 1, data)
      end
    end
  end

  def load_tweets(pages_to_load = PAGES_IN_BATCH)
    pages_to_load = PAGES_IN_BATCH if pages_to_load > PAGES_IN_BATCH || pages_to_load < 0
    data = fetch_tweet_data
    load_next_page(pages_to_load - 1, data)
    if data["results"] && !data["results"].empty?
      data["results"].sort_by {|hash| hash["created_at"]}.each {|hash| Tweet.from_data(hash) }
    end
    PROPERTIES.each {|p| self[p] = data[p.to_s]}
    save!
  end

  class FileFetcher
    def initialize(file)
      @file = file
    end

    def read
      File.read(@file)
    end
  end

  class TwitterFetcher
    attr_reader :uri

    def initialize(uri)
      @uri = uri
    end

    def read
      ::RestClient.get("http://search.twitter.com/search.json#{@uri}")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @items = ItemList.enumerator(20)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = ItemList.enumerator
  end

  def show
  end

  def new
    @item = Item.new
  end

  def create
    Item.create(params[:item])
    flash[:notice] = "Thanks, we added your item!"
    redirect_to :items
  end

  def edit
  end

  def update
  end

  def destroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  include Twitter::Autolink

  def item_classes(item)
    if item.class == Item
      "item"
    else
      "item #{item.class.css_name}"
    end
  end

  def render_item(item)
    partial = item.class.css_name
    partial = "items/#{partial}" unless controller_name == "items"
    render :partial => partial, :locals => { :item => item }
  end

  def tweet_author(tweet)
    auto_link("@#{tweet.from_user}").html_safe
  end

  def tweet_text(tweet)
    auto_link(tweet.content).html_safe
  end

  def tweet_icon(tweet)
    image_tag(tweet.profile_image_url, :size => '48x48', :alt => tweet.from_user)
  end
end

app/views/home/index.html.erb
<h1>JRubyHub</h1>

<%= render :partial => "items/list" %>

app/views/items/_form.html.erb
<div class="item_form">
  <%= form_for @item do |f| %>
    <%= f.label :content %><br/>
    <%= f.text_area :content %><br/>
    <%= f.submit "Create Item" %>
  <% end -%>
</div>

app/views/items/_item.html.erb
<div class="content">
  <%= item.content %>
</div>
<div class="when">
  Posted <%= time_ago_in_words(item.created_at) %> ago
</div>

app/views/items/_list.html.erb
<ol class="items">
<% @items.each do |item| -%>
  <li class="<%= item_classes(item) %>" id="item_<%= item.id %>">
<%= render_item(item) %>
  </li>
<% end -%>
</old>

app/views/items/_tweet.html.erb
<div>
  <div class="icon">
    <%= tweet_icon(item) %>
  </div>
</div>
<div class="tweet-body">
  <div class="content">
    <%= tweet_text(item) %>
  </div>
  <div class="when">
    Posted by <%= tweet_author(item) %> <a class="tweet-url" rel="nofollow" href="http://twitter.com/<%= item.from_user %>/status/<%= item.tweet_id %>"><%= time_ago_in_words(item.created_at) %> ago</a>
  </div>
</div>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/destroy.html.erb
<h1>Items#destroy</h1>
<p>Find me in app/views/items/destroy.html.erb</p>

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.html.erb
<h1>Items</h1>

<%= render :partial => "list" %>
<div class="actions">
  <%= link_to "Create New Item", new_item_path %>
</div>

app/views/items/new.html.erb
<h1>Items#new</h1>

<%= render :partial => "form" %>

app/views/items/show.html.erb
<h1>Items#show</h1>
<p>Find me in app/views/items/show.html.erb</p>

app/views/items/update.html.erb
<h1>Items#update</h1>
<p>Find me in app/views/items/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
  <title>JRubyHub</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js" %>
  <%= javascript_include_tag "rails" %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="main_nav">
    <div class="wrapper">
      <div id="menu" class="menu">
        <ul>
          <li id="page_1" class="depth-1 first">
            <a href="http://jruby.org/">Home</a>
          </li>
          <li id="page_5" class="depth-1">
            <a href="http://jruby.org/news">News</a>
          </li>
          <li id="page_8" class="depth-1">
            <a href="http://jruby.org/download">Download</a>
          </li>
          <li id="page_10" class="depth-1">
            <a href="http://jruby.org/getting-started">Getting Started</a>
          </li>
          <li id="page_9" class="depth-1">
            <a href="http://jruby.org/community">Community</a>
          </li>
          <li id="page_13" class="depth-1">
            <a href="http://jruby.org/documentation">Documentation</a>
          </li>
          <li id="page_15" class="depth-1">
            <a href="http://jruby.org/security">Security</a>
          </li>
          <li id="page_14" class="depth-1 last">
            <a href="http://jruby.org/contribute">Contribute</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div id="container">
    <div id="header">
      <a href="/"><img src="http://jruby.org/images/white_header_logo.png"></a>
      <h1>JRuby: 100% Pure-Java Implementation of the Ruby Programming Language.</h1>
    </div>
    <div id="content">
      <div id="white">
        <div class="body">
          <% if flash[:notice] -%>
          <div class="notice">
            <%= flash[:notice] %>
          </div>
          <% end -%>

          <%= yield %>
        </div>
      </div>
    </div>
  </div>
</body>
</html>